package tcc.internato.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ato_Indisciplinar.java
//  @ Date : 04/10/2016
//  @ Author : 
//
// 

@Entity
@Table(name = "ato_indisciplinar")
public class AtoIndisciplinar {
	@Column (name = "id_ato")
	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int id;

	@Column(name = "descricao_ato", nullable = false)
	public String descricao;

	@Column(name = "data_ato", nullable = false)
	public Date data;

	@Column(nullable = false)
	public Servidor associado;

	// getters e setters

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescricao_ato() {
		return descricao;
	}

	public void setDescricao_ato(String descricao_ato) {
		this.descricao = descricao_ato;
	}

	public Date getData_ato() {
		return data;
	}

	public void setData_ato(Date data_ato) {
		this.data = data_ato;
	}

	public Servidor getAssociado() {
		return associado;
	}

	public void setAssociado(Servidor associado) {
		this.associado = associado;
	}
}
