package tcc.internato.model;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import tcc.internato.enumeration.TipoPresenca;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Chamada.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//

@Entity
@Table(name = "chamada")
public class Chamada extends EntidadeBase {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_chamada")
	public Long id;

	@Column(name = "data", nullable = false)
	public Date data;

	@Column(nullable = false)
	@Enumerated(EnumType.ORDINAL)
	public TipoPresenca presenca;

	@Column(nullable = true)
	public String justificativa;

	// // // RELACIONAMENTOS ...

	// Uma Chamada esta associada a muitos Internos.
	// TODO acertar mapeamento abaixo para ManyToMany
	// @OneToMany(cascade = {
	// CascadeType.REFRESH }, targetEntity = Interno.class, fetch =
	// FetchType.LAZY, mappedBy = "chamada")
	// private List<Interno> internos;

	// Muitas Chamada esta associada a um Quartos.
	@ManyToOne(fetch = FetchType.LAZY, cascade = { CascadeType.REFRESH })
	@JoinColumn(name = "quartos_fk", nullable = false)
	private Quarto quartos;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getData() {
		return data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public TipoPresenca getPresenca() {
		return presenca;
	}

	public void setPresenca(TipoPresenca presenca) {
		this.presenca = presenca;
	}

	public String getJustificativa() {
		return justificativa;
	}

	public void setJustificativa(String justificativa) {
		this.justificativa = justificativa;
	}

	public Quarto getQuartos() {
		return quartos;
	}

	public void setQuartos(Quarto quartos) {
		this.quartos = quartos;
	}

}
