package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Endereco.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//

//@Entity
public class Endereco {
	@Column(name = "id_endereco")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(name = "cidade_interno", nullable = false)
	public String cidade;

	@Column(name = "estado_interno", nullable = false)
	public String estado;

	@Column(name = "cep_interno", nullable = false)
	public int cep;

	@Column(name = "endereco_interno", nullable = false)
	public String endereco;

	@Column(name = "avenida_interno", nullable = false)
	public String avenida;

	@Column(name = "apt_interno")
	public String apt;

	@Column(name = "numero_casa_interno")
	public int numero;

	@Column(nullable = false)
	public String reside_com;

	// getters e setters

	public Long getId_endereco() {
		return id;
	}

	public void setId_endereco(Long id_endereco) {
		this.id = id_endereco;
	}

	public String getCidade_interno() {
		return cidade;
	}

	public void setCidade_interno(String cidade_interno) {
		this.cidade = cidade_interno;
	}

	public String getEstado_interno() {
		return estado;
	}

	public void setEstado_interno(String estado_interno) {
		this.estado = estado_interno;
	}

	public int getCep_interno() {
		return cep;
	}

	public void setCep_interno(int cep_interno) {
		this.cep = cep_interno;
	}

	public String getEndereco_interno() {
		return endereco;
	}

	public void setEndereco_interno(String endereco_interno) {
		this.endereco = endereco_interno;
	}

	public String getAvenida_interno() {
		return avenida;
	}

	public void setAvenida_interno(String avenida_interno) {
		this.avenida = avenida_interno;
	}

	public String getApt_interno() {
		return apt;
	}

	public void setApt_interno(String apt_interno) {
		this.apt = apt_interno;
	}

	public int getNumero_casa_interno() {
		return numero;
	}

	public void setNumero_casa_interno(int numero_casa_interno) {
		this.numero = numero_casa_interno;
	}

	public String getReside_com() {
		return reside_com;
	}

	public void setReside_com(String reside_com) {
		this.reside_com = reside_com;
	}

}
