package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Endereco.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//
import javax.persistence.Table;

@Entity
@Table(name = "endereco")
public class Endereco extends EntidadeBase {
	@Column(name = "id_endereco")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(nullable = false)
	public String cidade;

	@Column(length = 2, nullable = false)
	public String uf;

	@Column(length = 8, nullable = false)
	public int cep;

	@Column(nullable = false)
	public String bairro;

	@Column(length = 1000, nullable = false)
	public String logradouro;

	@Column
	public int numero;

	@Column(length = 10)
	public String complemento;

	@Column(name = "reside_com", nullable = false)
	public String resideCom;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCidade() {
		return cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getUf() {
		return uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	public int getCep() {
		return cep;
	}

	public void setCep(int cep) {
		this.cep = cep;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getLogradouro() {
		return logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public int getNumero() {
		return numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public String getComplemento() {
		return complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getResideCom() {
		return resideCom;
	}

	public void setResideCom(String resideCom) {
		this.resideCom = resideCom;
	}

	// getters e setters

}
