package tcc.internato.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ocorrencia.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//

//@Entity
public class Ocorrencia {
	@Id
	@GeneratedValue
	public Long id_ocorrencia;

	@Column(nullable = false)
	public Date data_ocorrencia;

	@Column(nullable = false)
	public String descricao_ocorrencia;
}
