package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pais.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//

@Entity
@Table(name = "pais")
public class Pais extends EntidadeBase {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(name = "nome_pai")
	public String nomePai;

	@Column(name = "profissao_pai")
	public String profissaoPai;

	@Column(name = "nome_mae")
	public String nomeMae;

	@Column(name = "profissao_mae")
	public String profissaoMae;

	@Column(name = "telefone_pai")
	public int telefonePai;

	@Column(name = "telefone_mae")
	public int telefoneMae;

	@Column(name = "email_responsavel")
	public String emailReponsavel;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNomePai() {
		return nomePai;
	}

	public void setNomePai(String nomePai) {
		this.nomePai = nomePai;
	}

	public String getProfissaoPai() {
		return profissaoPai;
	}

	public void setProfissaoPai(String profissaoPai) {
		this.profissaoPai = profissaoPai;
	}

	public String getNomeMae() {
		return nomeMae;
	}

	public void setNomeMae(String nomeMae) {
		this.nomeMae = nomeMae;
	}

	public String getProfissaoMae() {
		return profissaoMae;
	}

	public void setProfissaoMae(String profissaoMae) {
		this.profissaoMae = profissaoMae;
	}

	public int getTelefonePai() {
		return telefonePai;
	}

	public void setTelefonePai(int telefonePai) {
		this.telefonePai = telefonePai;
	}

	public int getTelefoneMae() {
		return telefoneMae;
	}

	public void setTelefoneMae(int telefoneMae) {
		this.telefoneMae = telefoneMae;
	}

	public String getEmailReponsavel() {
		return emailReponsavel;
	}

	public void setEmailReponsavel(String emailReponsavel) {
		this.emailReponsavel = emailReponsavel;
	}

	// getters e setters

}
