package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pais.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//



@Entity
public class Pais {
	@Id
	@GeneratedValue
	private Long id_pais;
	
	@Column 
	public String nome_pai;
	
	@Column
	public String profissao_pai;
	
	@Column
	public String nome_mae;
	
	@Column
	public String profissao_mae;
	
	@Column
	public int telefone_pai;
	
	@Column
	public int telefone_mae;
	
	@Column
	public String email_reponsavel;

	//getters e setters 
	
	public Long getId_pais() {
		return id_pais;
	}

	public void setId_pais(Long id_pais) {
		this.id_pais = id_pais;
	}

	public String getNome_pai() {
		return nome_pai;
	}

	public void setNome_pai(String nome_pai) {
		this.nome_pai = nome_pai;
	}

	public String getProfissao_pai() {
		return profissao_pai;
	}

	public void setProfissao_pai(String profissao_pai) {
		this.profissao_pai = profissao_pai;
	}

	public String getNome_mae() {
		return nome_mae;
	}

	public void setNome_mae(String nome_mae) {
		this.nome_mae = nome_mae;
	}

	public String getProfissao_mae() {
		return profissao_mae;
	}

	public void setProfissao_mae(String profissao_mae) {
		this.profissao_mae = profissao_mae;
	}

	public int getTelefone_pai() {
		return telefone_pai;
	}

	public void setTelefone_pai(int telefone_pai) {
		this.telefone_pai = telefone_pai;
	}

	public int getTelefone_mae() {
		return telefone_mae;
	}

	public void setTelefone_mae(int telefone_mae) {
		this.telefone_mae = telefone_mae;
	}

	public String getEmail_reponsavel() {
		return email_reponsavel;
	}

	public void setEmail_reponsavel(String email_reponsavel) {
		this.email_reponsavel = email_reponsavel;
	}
	
}
