package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pessoa.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//

@Entity
@Table(name = "pessoa")
@Inheritance(strategy = InheritanceType.JOINED)
public class Pessoa extends EntidadeBase {

	@Id
	@Column(name = "id_pessoa")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(name = "nome_pessoa", nullable = false)
	private String nome;

	@Column(name = "cpf_pessoa", nullable = false)
	private int cpf;

	@Column(name = "matricula_pessoa", nullable = false)
	public String matricula;

	// getters e setters

	public Long getId_pessoa() {
		return id;
	}

	public void setId_pessoa(Long id_pessoa) {
		this.id = id_pessoa;
	}

	public String getNome_pessoa() {
		return nome;
	}

	public void setNome_pessoa(String nome_pessoa) {
		this.nome = nome_pessoa;
	}

	public int getCpf_pessoa() {
		return cpf;
	}

	public void setCpf_pessoa(int cpf_pessoa) {
		this.cpf = cpf_pessoa;
	}

	public String getMatricula_pessoa() {
		return matricula;
	}

	public void setMatricula_pessoa(String matricula_pessoa) {
		this.matricula = matricula_pessoa;
	}

	public String getTelefone_pessoa() {
		return telefone_pessoa;
	}

	public void setTelefone_pessoa(String telefone_pessoa) {
		this.telefone_pessoa = telefone_pessoa;
	}

	public String getEmail_pessoa() {
		return email_pessoa;
	}

	public void setEmail_pessoa(String email_pessoa) {
		this.email_pessoa = email_pessoa;
	}

	@Column
	public String telefone_pessoa;

	@Column
	public String email_pessoa;

}
