package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Quarto.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//

@Entity
public class Quarto {
	@Column
	@Id
	@GeneratedValue
	public Long id_quarto;

	//getter e setter
	
	public Long getId_quarto() {
		return id_quarto;
	}

	public void setId_quarto(Long id_quarto) {
		this.id_quarto = id_quarto;
	}
	
}
