package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Regulamento.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//
@Entity
public class Regulamento {
	@Id
	@GeneratedValue
	private Long id_regulamento;
	
	@Column(nullable = false)
	public String apelido_regulamento;
	
	@Column(nullable = false)
	public String descricao_regulamento;

	//getters e setters
	
	
	public Long getId_regulamento() {
		return id_regulamento;
	}

	public void setId_regulamento(Long id_regulamento) {
		this.id_regulamento = id_regulamento;
	}

	public String getApelido_regulamento() {
		return apelido_regulamento;
	}

	public void setApelido_regulamento(String apelido_regulamento) {
		this.apelido_regulamento = apelido_regulamento;
	}

	public String getDescricao_regulamento() {
		return descricao_regulamento;
	}

	public void setDescricao_regulamento(String descricao_regulamento) {
		this.descricao_regulamento = descricao_regulamento;
	}
	
}
