package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Regulamento.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//
@Entity
@Table(name = "regulamento")
public class Regulamento {

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(name = "apelido", nullable = false)
	private String apelido;

	@Column(name = "descricao", nullable = false)
	private String descricao;

	// getters e setters

	public Long getId_regulamento() {
		return id;
	}

	public void setId_regulamento(Long id_regulamento) {
		this.id = id_regulamento;
	}

	public String getApelido_regulamento() {
		return apelido;
	}

	public void setApelido_regulamento(String apelido_regulamento) {
		this.apelido = apelido_regulamento;
	}

	public String getDescricao_regulamento() {
		return descricao;
	}

	public void setDescricao_regulamento(String descricao_regulamento) {
		this.descricao = descricao_regulamento;
	}

}
