package tcc.internato.model;

import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Servidor.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//

@Entity
@Table(name = "servidor")
@PrimaryKeyJoinColumn(name = "id_servidor")
public class Servidor extends Pessoa {

	// RELACIONAMENTOS ...

	// TODO
	// // Um servidor esta associado a muitos atos indisciplinares.
	// @OneToMany(cascade = CascadeType.REFRESH, fetch = FetchType.LAZY,
	// mappedBy = "servidor")
	// @JoinColumn(name = "servidor_fk")
	// private List<AtoIndisciplinar> atoindisciplinares;
	//
	// // um servidor está associada a 0 ou muitas vistorias.
	// @OneToMany(cascade = CascadeType.REFRESH, fetch = FetchType.LAZY,
	// mappedBy = "servidor")
	// @JoinColumn(name = "servidor_fk")
	// private List<Vistoria> vistoria;
	//
	// public List<AtoIndisciplinar> getAtoindisciplinares() {
	// return atoindisciplinares;
	// }
	//
	// public void setAtoindisciplinares(List<AtoIndisciplinar>
	// atoindisciplinares) {
	// this.atoindisciplinares = atoindisciplinares;
	// }
	//
	// public List<Vistoria> getVistoria() {
	// return vistoria;
	// }
	//
	// public void setVistoria(List<Vistoria> vistoria) {
	// this.vistoria = vistoria;
	// }

	// GETTERS E SETTERS ...

}
