package tcc.internato.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Servidor.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//



@Entity
public class Servidor extends Pessoa {
	@Column (name = "id_servidor")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	// getter e setter
	
	public Long getId_servidor() {
		return id;
	}

	public void setId_servidor(Long id_servidor) {
		this.id = id_servidor;
	}
	
}
