package tcc.internato.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vistoria.java
//  @ Date : 04/10/2016
//  @ Author : 
//
//
@Entity
public class Vistoria {
	@Id
	@GeneratedValue
	private Long id_vistoria;
	
	@Column(nullable = false)
	public Date data_vistoria;
	
	@Column(nullable = false)
	public int nota_limpeza;
	
}
